# Environment type:
#  - 0 = development
#  - 1 = production
#environment: 0

# HTTP binding address
address: :8080

# Allowed cross-origin addresses (array)
cors:
  - http://localhost:8080
  - http://localhost:3000
#  - http://10.0.2.2:8041

# JWT secret
jwtsecret: nfkmklrnfmelwmkjewdnlwejfjewkfklewnjkbuismjnvjbeofrmdopkeopjewf

# PostgreSQL server address
postgresdsn: "host=mnt.bsthun.com user=going_going password=GoingGoingMAC dbname=going_going port=8031 sslmode=disable TimeZone=Asia/Shanghai"
